// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quanlybanthuoc.Data;

#nullable disable

namespace quanlybanthuoc.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20251205003058_AddPaymentFieldsToDonHang")]
    partial class AddPaymentFieldsToDonHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.ChiNhanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenChiNhanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__ChiNhanh__3214EC276A4EAE4E");

                    b.ToTable("ChiNhanh", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("IddonHang")
                        .HasColumnType("int")
                        .HasColumnName("IDDonHang");

                    b.Property<int?>("Idthuoc")
                        .HasColumnType("int")
                        .HasColumnName("IDThuoc");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__ChiTietD__3214EC274C1EB300");

                    b.HasIndex("IddonHang");

                    b.HasIndex("Idthuoc");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__DanhMuc__3214EC273AFD2730");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonGiaoHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IddonHang")
                        .HasColumnType("int")
                        .HasColumnName("IDDonHang");

                    b.Property<int?>("IdnguoiGiaoHang")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiGiaoHang");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayBatDauGiao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayGiaoThanhCong")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayLayHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("PhiGiaoHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiGiaoHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__DonGiaoH__3214EC27327CC0D8");

                    b.HasIndex("IddonHang");

                    b.HasIndex("IdnguoiGiaoHang");

                    b.ToTable("DonGiaoHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdchiNhanh")
                        .HasColumnType("int")
                        .HasColumnName("IDChiNhanh");

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.Property<int?>("IdnguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiDung");

                    b.Property<int?>("IdphuongThucTt")
                        .HasColumnType("int")
                        .HasColumnName("IDPhuongThucTT");

                    b.Property<string>("LoaiDonHang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("TAI_CHO");

                    b.Property<string>("MomoOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MomoTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TienGiamGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING_PAYMENT");

                    b.HasKey("Id")
                        .HasName("PK__DonHang__3214EC277750CAF3");

                    b.HasIndex("IdchiNhanh");

                    b.HasIndex("IdkhachHang");

                    b.HasIndex("IdnguoiDung");

                    b.HasIndex("IdphuongThucTt");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonNhapHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdchiNhanh")
                        .HasColumnType("int")
                        .HasColumnName("IDChiNhanh");

                    b.Property<int?>("IdnguoiNhan")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiNhan");

                    b.Property<int?>("IdnhaCungCap")
                        .HasColumnType("int")
                        .HasColumnName("IDNhaCungCap");

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<string>("SoDonNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__DonNhapH__3214EC2796C33929");

                    b.HasIndex("IdchiNhanh");

                    b.HasIndex("IdnguoiNhan");

                    b.HasIndex("IdnhaCungCap");

                    b.ToTable("DonNhapHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__KhachHan__3214EC27D33ED7C9");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.KhoHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdchiNhanh")
                        .HasColumnType("int")
                        .HasColumnName("IDChiNhanh");

                    b.Property<int?>("IdloHang")
                        .HasColumnType("int")
                        .HasColumnName("IDLoHang");

                    b.Property<DateOnly?>("NgayCapNhat")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TonKhoToiThieu")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__KhoHang__3214EC27B0C42972");

                    b.HasIndex("IdchiNhanh");

                    b.HasIndex("IdloHang");

                    b.ToTable("KhoHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.LichSuDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiemCong")
                        .HasColumnType("int");

                    b.Property<int?>("DiemTru")
                        .HasColumnType("int");

                    b.Property<int?>("IddonHang")
                        .HasColumnType("int")
                        .HasColumnName("IDDonHang");

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.Property<DateOnly?>("NgayGiaoDich")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__LichSuDi__3214EC27515C334A");

                    b.HasIndex("IddonHang");

                    b.HasIndex("IdkhachHang");

                    b.ToTable("LichSuDiem", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.LoHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("IddonNhapHang")
                        .HasColumnType("int")
                        .HasColumnName("IDDonNhapHang");

                    b.Property<int?>("Idthuoc")
                        .HasColumnType("int")
                        .HasColumnName("IDThuoc");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySanXuat")
                        .HasColumnType("date");

                    b.Property<string>("SoLo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__LoHang__3214EC27E2F8B59C");

                    b.HasIndex("IddonNhapHang");

                    b.HasIndex("Idthuoc");

                    b.ToTable("LoHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdchiNhanh")
                        .HasColumnType("int")
                        .HasColumnName("IDChiNhanh");

                    b.Property<int?>("IdvaiTro")
                        .HasColumnType("int")
                        .HasColumnName("IDVaiTro");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__NguoiDun__3214EC27F63D204A");

                    b.HasIndex("IdchiNhanh");

                    b.HasIndex("IdvaiTro");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC08881EDE8")
                        .IsUnique()
                        .HasFilter("[TenDangNhap] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NguoiGiaoHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BienSoXe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdchiNhanh")
                        .HasColumnType("int")
                        .HasColumnName("IDChiNhanh");

                    b.Property<DateOnly?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__NguoiGia__3214EC2700EFEB1C");

                    b.HasIndex("IdchiNhanh");

                    b.ToTable("NguoiGiaoHang", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__NhaCungC__3214EC27109C5C47");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenPhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__PhuongTh__3214EC2792E6D7AF");

                    b.ToTable("PhuongThucThanhToan", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BiThuHoi")
                        .HasColumnType("bit");

                    b.Property<bool?>("ConHieuLuc")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaHetHan")
                        .HasColumnType("bit");

                    b.Property<int?>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThuHoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07F3D5165D");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.Thuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DonVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HoatChat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IddanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("IDDanhMuc");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Thuoc__3214EC27B61315F8");

                    b.HasIndex("IddanhMuc");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__VaiTro__3214EC275737342A");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.VwBaoCaoDoanhThu", b =>
                {
                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int?>("IdchiNhanh")
                        .HasColumnType("int")
                        .HasColumnName("IDChiNhanh");

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.Property<int?>("IdnguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiDung");

                    b.Property<int?>("IdphuongThucTt")
                        .HasColumnType("int")
                        .HasColumnName("IDPhuongThucTT");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuongSanPham")
                        .HasColumnType("int");

                    b.Property<string>("TenChiNhanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhanVien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenPhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TienGiamGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TongSoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.ToTable((string)null);

                    b.ToView("vw_BaoCaoDoanhThu", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.VwThongKeThuocBanChay", b =>
                {
                    b.Property<string>("DonVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaTrungBinh")
                        .HasColumnType("decimal(38, 6)");

                    b.Property<string>("HoatChat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoDonHang")
                        .HasColumnType("int");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuocId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<int?>("TongSoLuongBan")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ThongKeThuocBanChay", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.VwThongKeTonKho", b =>
                {
                    b.Property<int>("DaHetHan")
                        .HasColumnType("int");

                    b.Property<string>("DonVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GiaTriTonKho")
                        .HasColumnType("decimal(29, 2)");

                    b.Property<int?>("IdchiNhanh")
                        .HasColumnType("int")
                        .HasColumnName("IDChiNhanh");

                    b.Property<int?>("Idthuoc")
                        .HasColumnType("int")
                        .HasColumnName("IDThuoc");

                    b.Property<int>("KhoHangId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayCapNhat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<int>("SapHetHan")
                        .HasColumnType("int");

                    b.Property<string>("SoLo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenChiNhanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TonKhoThap")
                        .HasColumnType("int");

                    b.Property<int?>("TonKhoToiThieu")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ThongKeTonKho", (string)null);
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.DonHang", "IddonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IddonHang")
                        .HasConstraintName("FK__ChiTietDo__IDDon__5535A963");

                    b.HasOne("quanlybanthuoc.Data.Entities.Thuoc", "IdthuocNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Idthuoc")
                        .HasConstraintName("FK__ChiTietDo__IDThu__5629CD9C");

                    b.Navigation("IddonHangNavigation");

                    b.Navigation("IdthuocNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonGiaoHang", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.DonHang", "IddonHangNavigation")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("IddonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DonGiaoHang_DonHang");

                    b.HasOne("quanlybanthuoc.Data.Entities.NguoiGiaoHang", "IdnguoiGiaoHangNavigation")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("IdnguoiGiaoHang")
                        .HasConstraintName("FK_DonGiaoHang_NguoiGiaoHang");

                    b.Navigation("IddonHangNavigation");

                    b.Navigation("IdnguoiGiaoHangNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonHang", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.ChiNhanh", "IdchiNhanhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdchiNhanh")
                        .HasConstraintName("FK__DonHang__IDChiNh__5812160E");

                    b.HasOne("quanlybanthuoc.Data.Entities.KhachHang", "IdkhachHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdkhachHang")
                        .HasConstraintName("FK__DonHang__IDKhach__59063A47");

                    b.HasOne("quanlybanthuoc.Data.Entities.NguoiDung", "IdnguoiDungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdnguoiDung")
                        .HasConstraintName("FK__DonHang__IDNguoi__59FA5E80");

                    b.HasOne("quanlybanthuoc.Data.Entities.PhuongThucThanhToan", "IdphuongThucTtNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdphuongThucTt")
                        .HasConstraintName("FK__DonHang__IDPhuon__5AEE82B9");

                    b.Navigation("IdchiNhanhNavigation");

                    b.Navigation("IdkhachHangNavigation");

                    b.Navigation("IdnguoiDungNavigation");

                    b.Navigation("IdphuongThucTtNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonNhapHang", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.ChiNhanh", "IdchiNhanhNavigation")
                        .WithMany("DonNhapHangs")
                        .HasForeignKey("IdchiNhanh")
                        .HasConstraintName("FK__DonNhapHa__IDChi__5BE2A6F2");

                    b.HasOne("quanlybanthuoc.Data.Entities.NguoiDung", "IdnguoiNhanNavigation")
                        .WithMany("DonNhapHangs")
                        .HasForeignKey("IdnguoiNhan")
                        .HasConstraintName("FK__DonNhapHa__IDNgu__5CD6CB2B");

                    b.HasOne("quanlybanthuoc.Data.Entities.NhaCungCap", "IdnhaCungCapNavigation")
                        .WithMany("DonNhapHangs")
                        .HasForeignKey("IdnhaCungCap")
                        .HasConstraintName("FK__DonNhapHa__IDNha__5DCAEF64");

                    b.Navigation("IdchiNhanhNavigation");

                    b.Navigation("IdnguoiNhanNavigation");

                    b.Navigation("IdnhaCungCapNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.KhoHang", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.ChiNhanh", "IdchiNhanhNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("IdchiNhanh")
                        .HasConstraintName("FK__KhoHang__IDChiNh__5EBF139D");

                    b.HasOne("quanlybanthuoc.Data.Entities.LoHang", "IdloHangNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("IdloHang")
                        .HasConstraintName("FK__KhoHang__IDLoHan__5FB337D6");

                    b.Navigation("IdchiNhanhNavigation");

                    b.Navigation("IdloHangNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.LichSuDiem", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.DonHang", "IddonHangNavigation")
                        .WithMany("LichSuDiems")
                        .HasForeignKey("IddonHang")
                        .HasConstraintName("FK__LichSuDie__IDDon__60A75C0F");

                    b.HasOne("quanlybanthuoc.Data.Entities.KhachHang", "IdkhachHangNavigation")
                        .WithMany("LichSuDiems")
                        .HasForeignKey("IdkhachHang")
                        .HasConstraintName("FK__LichSuDie__IDKha__619B8048");

                    b.Navigation("IddonHangNavigation");

                    b.Navigation("IdkhachHangNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.LoHang", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.DonNhapHang", "IddonNhapHangNavigation")
                        .WithMany("LoHangs")
                        .HasForeignKey("IddonNhapHang")
                        .HasConstraintName("FK__LoHang__IDDonNha__628FA481");

                    b.HasOne("quanlybanthuoc.Data.Entities.Thuoc", "IdthuocNavigation")
                        .WithMany("LoHangs")
                        .HasForeignKey("Idthuoc")
                        .HasConstraintName("FK__LoHang__IDThuoc__6383C8BA");

                    b.Navigation("IddonNhapHangNavigation");

                    b.Navigation("IdthuocNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NguoiDung", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.ChiNhanh", "IdchiNhanhNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("IdchiNhanh")
                        .HasConstraintName("FK__NguoiDung__IDChi__6477ECF3");

                    b.HasOne("quanlybanthuoc.Data.Entities.VaiTro", "IdvaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("IdvaiTro")
                        .HasConstraintName("FK__NguoiDung__IDVai__656C112C");

                    b.Navigation("IdchiNhanhNavigation");

                    b.Navigation("IdvaiTroNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NguoiGiaoHang", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.ChiNhanh", "IdchiNhanhNavigation")
                        .WithMany("NguoiGiaoHangs")
                        .HasForeignKey("IdchiNhanh")
                        .HasConstraintName("FK_NguoiGiaoHang_ChiNhanh");

                    b.Navigation("IdchiNhanhNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.Thuoc", b =>
                {
                    b.HasOne("quanlybanthuoc.Data.Entities.DanhMuc", "IddanhMucNavigation")
                        .WithMany("Thuocs")
                        .HasForeignKey("IddanhMuc")
                        .HasConstraintName("FK__Thuoc__IDDanhMuc__6754599E");

                    b.Navigation("IddanhMucNavigation");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.ChiNhanh", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("DonNhapHangs");

                    b.Navigation("KhoHangs");

                    b.Navigation("NguoiDungs");

                    b.Navigation("NguoiGiaoHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DanhMuc", b =>
                {
                    b.Navigation("Thuocs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DonGiaoHangs");

                    b.Navigation("LichSuDiems");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.DonNhapHang", b =>
                {
                    b.Navigation("LoHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("LichSuDiems");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.LoHang", b =>
                {
                    b.Navigation("KhoHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("DonNhapHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NguoiGiaoHang", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.NhaCungCap", b =>
                {
                    b.Navigation("DonNhapHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LoHangs");
                });

            modelBuilder.Entity("quanlybanthuoc.Data.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
